In [1]:
#배열 축 추가: np.newaxis, np.tile

import numpy as np

In [3]:
a = np.array([1,2,3,4])
a
a.shape

(4,)

In [6]:
a41 = a[:,np.newaxis ]
a41
a41 = a[np.newaxis,:]
a41

array([[1, 2, 3, 4]])

In [12]:
b = np.arange(15).reshape(3,5)
b
b351 = b[: ,: , np.newaxis]
b351.shape

b351 = b[: , np.newaxis, :]
b351.shape

(3, 1, 5)

In [17]:
a = np.array([0,1,2,3])
a8 = np.tile(a,2)
a8

a32 = np.tile(a,(3,2))
a32

b = np.arange(8).reshape(2,4)
b28 = np.tile(b,2)
b28

b44 = np.tile(b,(2,1))
b44

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
#행렬의 내적: aT * a
a = np.arange(15).reshape(3,5)
a.T #행->열
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [27]:
a = np.arange(10)
a
ai = a[0:5]
ai[1:3] = 10
ai
a

array([ 0, 10, 10,  3,  4,  5,  6,  7,  8,  9])

In [29]:
arr = np.arange(20).reshape(5,4)
arr
abc = np.array(['a','a','b','c','c'])

In [43]:
arr[abc=='a']
arr[abc=='a',:]

arr[abc=='a',:2]
arr[abc=='a',2]

arr[abc!='a']
arr[~(abc=='a')]

arr[(abc=='a') | (abc=='b')]

arr[(abc!='a') & (abc!='b')]
# arr[(abc!='a') and (abc!='b')] 에러

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
# arr에서 abc배열을 이용하여 'a'와 같은 행은 모두 99로 변경 (불린 참조)
arr[abc=='a'] = 99
arr

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
# arr배열에서 20보다 큰 값은 모두 0으로 변경
arr[arr>=20] = 0
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
# arr배열에서 8이상 15이하의 값은 모두 0으로 변경
# arr[8<=arr<=15] = 0  #valueError
# arr[8<=arr & arr<=15] = 0  #valueError
arr[(8<=arr) & (arr<=15)] = 0
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [16, 17, 18, 19]])

In [54]:
a = np.array([-3.5, -2.5, 0, 1.6, 3.14, 4.05])
np.around(a) #0.5기준으로 내림 혹은 올림
np.round_(a,1) #소수이하 첫째자리까지 출력(둘째자리에서 반올림)
np.rint(a) #가까운 정수로 올림 또는 내림
np.fix(a) #0 방향으로 가까운 정수로 올림 또는 내림
np.ceil(a) #값보다 크거나 같은 가장 작은 정수값으로 올림
np.floor(a) #값보다 작거나 같은 가장 큰 정수값으로 내림
np.trunc(a) #소수 이하 버림. 정수만 출력

array([-3., -2.,  0.,  1.,  3.,  4.])

In [56]:
a = np.array([1,2,3,4])
c = np.arange(1,5).reshape(2,2)
c

array([[1, 2],
       [3, 4]])

In [59]:
#배열의 요소값 곱셈
np.prod(c) #24
np.prod(c, axis=0) #열 기준 곱셈
np.prod(c, axis=1) #행 기준 곱셈

array([ 2, 12])

In [64]:
np.sum(a) #0차원, 스칼라
a
np.sum(c, keepdims=True)
np.sum(c, axis=1)

array([3, 7])

In [70]:
d = np.array([[1,2],[3,np.nan]])
d
np.prod(d)
np.prod(d,axis=0)
np.prod(d,axis=1)

#np.nanprod: 곱셈할때 nan을 1로 간주해서 곱셈
np.nanprod(d,axis=0)

array([3., 2.])

In [73]:
d
np.sum(d)
np.nansum(d)

#np.nansum: 덧셈할때 nan을 0으로 간주해서 덧셈

6.0

In [78]:
a
b = np.arange(1,7).reshape(2,3)
b
np.cumprod(a) #누적 곱셈
np.cumprod(b,axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [80]:
# 자연상수e, y=logx or y=ln(x)
# 지수함수 : np.exp() 밑이 자연상수 e인 지수함수로 변환
x = np.array([0.00001, 1, 2, 10])
np.exp(x)

np.log(x)
np.log10(x)
np.log2(x)

array([-11.51292546,   0.        ,   0.69314718,   2.30258509])

In [81]:
#1

import pandas as pd
import numpy as np

In [85]:
df_score2_A = pd.DataFrame({'반':'A',
                            '번호':range(1,6),
                            '국어':[90,80,90,70,100],
                            '영어':[100,90,100,80,70],
                            '수학':[80,100,80,90,80]})
df_score2_B = pd.DataFrame({'반':'B',
                            '번호':range(1,6),
                            '국어':[80,90,100,70,80],
                            '영어':[90,100,70,80,90],
                            '수학':[100,70,80,90,100]})

In [88]:
df_score2 = pd.concat([df_score2_A, df_score2_B], ignore_index=True)
df_score2

반  번호   국어   영어   수학
0  A   1   90  100   80
1  A   2   80   90  100
2  A   3   90  100   80
3  A   4   70   80   90
4  A   5  100   70   80
5  B   1   80   90  100
6  B   2   90  100   70
7  B   3  100   70   80
8  B   4   70   80   90
9  B   5   80   90  100

In [90]:
#2

df1 = pd.pivot_table(df_score2, index=['반','번호'] )
df1

국어   수학   영어
반 번호               
A 1    90   80  100
  2    80  100   90
  3    90   80  100
  4    70   90   80
  5   100   80   70
B 1    80  100   90
  2    90   70  100
  3   100   80   70
  4    70   90   80
  5    80  100   90

In [91]:
#3

df1['평균'] = df1.mean(axis=1)
df1

국어   수학   영어         평균
반 번호                          
A 1    90   80  100  90.000000
  2    80  100   90  90.000000
  3    90   80  100  90.000000
  4    70   90   80  80.000000
  5   100   80   70  83.333333
B 1    80  100   90  90.000000
  2    90   70  100  86.666667
  3   100   80   70  83.333333
  4    70   90   80  80.000000
  5    80  100   90  90.000000

In [92]:
#4

df_score2

반  번호   국어   영어   수학
0  A   1   90  100   80
1  A   2   80   90  100
2  A   3   90  100   80
3  A   4   70   80   90
4  A   5  100   70   80
5  B   1   80   90  100
6  B   2   90  100   70
7  B   3  100   70   80
8  B   4   70   80   90
9  B   5   80   90  100

In [96]:
df3 = pd.pivot_table(df_score2, index='번호', columns='반' )
df3

국어        수학        영어     
반     A    B    A    B    A    B
번호                              
1    90   80   80  100  100   90
2    80   90  100   70   90  100
3    90  100   80   80  100   70
4    70   70   90   90   80   80
5   100   80   80  100   70   90

In [98]:
#5

df3.loc['평균'] = df3.mean(axis=0)
df3

국어            수학            영어       
반       A      B      A      B      A      B
번호                                          
1    90.0   80.0   80.0  100.0  100.0   90.0
2    80.0   90.0  100.0   70.0   90.0  100.0
3    90.0  100.0   80.0   80.0  100.0   70.0
4    70.0   70.0   90.0   90.0   80.0   80.0
5   100.0   80.0   80.0  100.0   70.0   90.0
평균   86.0   84.0   86.0   88.0   88.0   86.0