In [ ]:
import tensorflow as tf

In [ ]:
import nltk  #자연어(영어) 처리 도구
nltk.__version__

In [ ]:
nltk.download() #nltk data 다운로드
#nltk.download('treebank') #treebank 별도로 설치
#github.com/nltk

In [ ]:
#pip install konlpy
import konlpy

In [ ]:
#JPype: 자바와 파이썬 연결
from konlpy.tag import Kkma
kkma = Kkma()
print(kkma.morphs('자바와 파이썬 연결'))

In [1]:
#토큰화, 정제, 정규화
#토큰(단어)화: 어절,단어,문장,문단이 될 수도 있음
#단어 토큰화: 구두점,특수문자 제거
from nltk.tokenize import word_tokenize

In [2]:
#목적에 맞는 tokenizer 사용

In [3]:
print(word_tokenize("Mr. Jone's Don't be "))

['Mr.', 'Jone', "'s", 'Do', "n't", 'be']


In [4]:
from nltk.tokenize import WordPunctTokenizer

In [5]:
print(WordPunctTokenizer().tokenize("Mr. Jone's Don't be ")) 

['Mr', '.', 'Jone', "'", 's', 'Don', "'", 't', 'be']


In [6]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [7]:
print(text_to_word_sequence("Mr. Jone's Don't be!"))

['mr', "jone's", "don't", 'be']


In [8]:
#정규표현식을 잘 써야 전처리 => 양질의 데이터를 얻을 수 있음

In [9]:
from nltk.tokenize import TreebankWordTokenizer

In [10]:
twt=TreebankWordTokenizer()
print(twt.tokenize("Mr. Jone's Don't be!"))

['Mr.', 'Jone', "'s", 'Do', "n't", 'be', '!']


In [11]:
from nltk.tokenize import sent_tokenize
text = "Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."

In [12]:
print(sent_tokenize(text)) #token: 3개 => 토큰의 단위가 문장
print(len(sent_tokenize(text)))

['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.']
3


In [13]:
#조사: 그녀가(에게,를,와,는...)
#아버지가방에 들어가...
#한국어 토큰화 작업 : 형태소(가장 작은 말의 단위) 고려
#자립형태소(길동이,파이썬)/의존형태소(조사,어미.../가,을,합니다)
#ex)길동이가 파이썬을 합니다

In [14]:
#토큰화 과정에서 단어가 어떤 품사로 쓰였는지 구분하는 작업
#품사 태깅(tagging), fly
text = "Python is an interpreted, high-level, general-purpose programming language."
print(word_tokenize(text))
from nltk.tag import pos_tag
pos_tag(word_tokenize(text))

['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.']


[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('an', 'DT'),
 ('interpreted', 'JJ'),
 (',', ','),
 ('high-level', 'JJ'),
 (',', ','),
 ('general-purpose', 'JJ'),
 ('programming', 'NN'),
 ('language', 'NN'),
 ('.', '.')]

In [15]:
#형태소 분석기: Okt, Mecab, Kkma...
#단어토큰화가 아님. 형태소 단위로 토큰화를 하는 것 => 한국어
#단어토큰화 => 영어
from konlpy.tag import Okt

In [16]:
#Okt와 jpype버전이 맞지 않는 경우 에러가 발생
#jpype1 버전을 0.7.0으로 재설치
#pipe install jpype1==0.7.0
okt=Okt()
#mortphs: 형태소 추출
print(okt.morphs("오늘은 수요일, 내일은 목요일입니다"))
#pos: 품사 추출
print(okt.pos("오늘은 수요일, 내일은 목요일입니다"))
#nouns: 명사 추출
print(okt.nouns("오늘은 수요일, 내일은 목요일입니다"))
#konlpy.org 사이트 참고

['오늘', '은', '수요일', ',', '내일', '은', '목요일', '입니다']
[('오늘', 'Noun'), ('은', 'Josa'), ('수요일', 'Noun'), (',', 'Punctuation'), ('내일', 'Noun'), ('은', 'Josa'), ('목요일', 'Noun'), ('입니다', 'Adjective')]
['오늘', '수요일', '내일', '목요일']


In [17]:
# from konlpy.tag import Kkma
# kma = Kkma()
# kma.morphs()

In [18]:
#데이터 정제(전처리): 불필요한 형태소 제거, 단어 통일(밥,식사...)
#정규표현식을 이용

In [19]:
import numpy as np

# 특이값 분해 full SVD

In [21]:
A = np.array([[0,0,0,1,0,1,1,0,0],
              [0,0,0,1,1,0,1,0,0],
              [0,1,1,0,2,0,0,0,0],
              [1,0,0,0,0,0,0,1,1]])
np.shape(A)

(4, 9)

In [22]:
U,s,VT = np.linalg.svd(A,full_matrices=True) #full SVD, truncated SVD

In [23]:
U.shape

(4, 4)

In [24]:
U.round(2) #직교행렬

array([[-0.24,  0.75,  0.  , -0.62],
       [-0.51,  0.44, -0.  ,  0.74],
       [-0.83, -0.49, -0.  , -0.27],
       [-0.  , -0.  ,  1.  ,  0.  ]])

In [25]:
print(s.round(2)) #4
s.shape

[2.69 2.05 1.73 0.77]


(4,)

In [26]:
S = np.zeros((4,9))
S[:4,:4] = np.diag(s)
print(S.round(2)) #특이값 행렬

[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]


In [27]:
print(VT.round(2))

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


In [28]:
np.dot(np.dot(U,S),VT).round(2)

array([[ 0.,  0.,  0.,  1., -0.,  1.,  1.,  0.,  0.],
       [ 0., -0., -0.,  1.,  1., -0.,  1., -0., -0.],
       [ 0.,  1.,  1., -0.,  2., -0., -0.,  0.,  0.],
       [ 1., -0.,  0.,  0., -0.,  0., -0.,  1.,  1.]])

In [29]:
np.allclose(A,np.dot(np.dot(U,S),VT).round(2))

True

In [30]:
##절단된(truncated) SVD
##토픽 2개
S = S[:2,:2]
print(S.round(2))

[[2.69 0.  ]
 [0.   2.05]]


In [31]:
U.shape #4,4
U = U[:,:2] #4,2 #문서4개, 토픽2
#U의 의미는 4개 문서 각각에 대한 잠재된 의미를 표현하고 있는 수치 문서 벡터
U.round(2)

array([[-0.24,  0.75],
       [-0.51,  0.44],
       [-0.83, -0.49],
       [-0.  , -0.  ]])

In [32]:
VT.shape #(9,9)
VT = VT[:2,:] #(2,9) #토픽*단어 개수
#VT의 각 열은 잠재 의미를 나타내기 위한 수치화된 단어 벡터
VT.round(2)
#U*S*VT != A

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ]])

In [34]:
Aprime = np.dot(np.dot(U,S),VT)
print(Aprime.round(2))
print(A)

[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.    0.    0.    0.  ]]
[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]


In [37]:
np.dot(S,VT).round(2)

array([[-0.  , -0.83, -0.83, -0.75, -2.16, -0.24, -0.75, -0.  , -0.  ],
       [ 0.  , -0.49, -0.49,  1.2 , -0.53,  0.75,  1.2 , -0.  , -0.  ]])

## 코사인 유사도로 유사한 문서 찾기

In [38]:
"""
           돈      사랑      저는      좋아요
줄거리1    0        1          1          1
줄거리2    1        0          1          1
줄거리3    2        0          2          2


"""
from numpy.linalg import norm

In [39]:
mov1 = np.array([0,1,1,1])
mov2 = np.array([1,0,1,1])
mov3 = np.array([2,0,2,2])

In [46]:
np.dot(mov1,mov2) #두 벡터의 내적
np.dot(mov1,mov2)/(norm(mov1)*norm(mov2))

def cos_sim(X,Y):
    return np.dot(X,Y)/(norm(X)*norm(Y))

In [47]:
print(cos_sim(mov1,mov2))
print(cos_sim(mov2,mov3))
print(cos_sim(mov1,mov3))

0.6666666666666667
1.0000000000000002
0.6666666666666667


In [49]:
import pandas as pd

In [52]:
data = pd.read_csv("movies_metadata.csv/movies_metadata.csv")
data.shape

(45466, 24)

In [53]:
data = data.head(20000)

In [56]:
data['overview'].isnull().sum()
data['overview'] = data['overview'].fillna('')

In [57]:
data['overview'].isnull().sum()

0

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
tfidf_mat = tfidf.fit_transform(data['overview'])
tfidf_mat.shape

(20000, 47487)