In [1]:
#신경망 구현(라이브러리 X)

In [5]:
import numpy as np
X = np.array([1,2,3,4])
np.ndim(X) #몇 차원 배열인지 출력 : 1차원 배열
#차원의 수
X.shape[0] #(4,) : 1차원
#(2,3) : 2차원
#(2,3,4) : 3차원....n차원

4

In [8]:
X = np.array([[1,2],[3,4],[5,6]]) #2차원 배열
np.ndim(X)
X.shape #(3, 2) => 3행2열
#0번째 차원, 1번째 차원

(3, 2)

In [10]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
#행렬의 곱(내적) XY => 교환법칙 성립X
print(np.dot(X,Y))
print(np.dot(Y,X)) 

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [14]:
X = np.array([1,2])
X.shape
W = np.array([[1,3,5],[2,4,6]])
print(np.dot(X,W))

[ 5 11 17]


In [17]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [21]:
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]]) #(2,3)
B1 = np.array([0.1,0.2,0.3])
H1 = np.dot(X,W1)+B1
H1
Z1 = sigmoid(H1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [22]:
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])
H2 = np.dot(Z1,W2)+B2
Z2 = sigmoid(H2)

In [23]:
W3 = np.array([[0.1,0.2],[0.2,0.3]])
B3 = np.array([0.1,0.2])
H3 = np.dot(Z2,W3)+B3
print(H3)

[0.31682708 0.55655308]


In [25]:
scores = np.array([20,10,1])
exp_s = np.exp(scores) #지수 함수 

In [26]:
sum_exp_s = np.sum(exp_s) #지수 함수의 합
sum_exp_s

485187224.5938669

In [27]:
y = exp_s/sum_exp_s
y

array([9.99954597e-01, 4.53978684e-05, 5.60254205e-09])

In [29]:
def myRelu(x):
    return np.maximum(0,x)

In [31]:
X = np.array([2,5])
W1 = np.array([[1,2,3],[4,5,6]])
H1 = np.dot(X,W1)
Z1 = myRelu(H1)
Z1

array([22, 29, 36])

In [32]:
W2 = np.array([[1,2],[3,4],[5,6]])
H2 = np.dot(Z1,W2)
H2

array([289, 376])

In [33]:
W3 = np.array([[1],[2]])
Z = np.dot(H2,W3)
Z

array([1041])